### ISSUE TITLE
allow parsnip models for weight estimation

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#209]
We could use tidymodels + parsnip for allowing all kinds of models for IPCW estimation.

- only logistic regression?
- also "classification" models?
- Wrapper for fitting, saving, predicting

**Comment by lisu-stats** [comment]
@gravesti Shaun and I will look into highly adaptive LASSO in this paper [https://onlinelibrary.wiley.com/doi/abs/10.1111/biom.13719](url)

**Comment by gravesti** [comment]
@lisu-stats 
Regarding HAL, I see there is a `hal9001` package. It should be simple enough to support.

I have now merged the `parsnip` functionality, so we have access to many models:
https://parsnip.tidymodels.org/articles/Examples.html

You can recreate the standard glm method:
```r
 trial_sequence("PP") |>
   set_data(data = data_censored) |>
   set_switch_weight_model(
     numerator = ~ age_s + x1 + x3,
     denominator = ~ x3 + x4,
     model_fitter = parsnip_model(
      parsnip::logistic_reg() |> set_mode("classification") |> set_engine("glm"),
      tempdir()
    )
   ) |> calculate_weights()
```

Or something more exotic like MARS
```r

library(earth)
mars_spec <- mars(prod_degree = 1, prune_method = "backward") %>% 
    set_mode("classification") %>% 
    set_engine("earth")

  parsnip_model(mars_spec, tempdir())
```

**Comment by lisu-stats** [comment]
Thanks @gravesti Yes, `hal9001` is the package we can use for HAL.  I will discuss with Shaun about an undersmoothed version of HAL which is more suitable to weight estimation. 

For `parsnip` models, will the specific libraries  be automatically loaded? or users have to do it manually.

**Comment by gravesti** [comment]
@lisu-stats From my testing it seems they will actually be loaded automatically at fitting time.
It also seems that many of the modelling packages are installed when you install parsnip.

**Comment by lisu-stats** [comment]
Thanks @gravesti Using data-adaptive methods to estimate weights can generate problems when drawing inference, e.g. using bootstrap. However, people are doing this in practice... so I don't know. 

The undersmoothed HAL has some theoretical support for their validity to estimate IPTW weights. Alternatively, double robust methods such as this one https://www.jstatsoft.org/article/view/v081i01/1153
can be used, but it is much more sophisticated and is not available to fit general MSMs yet.

**Comment by lisu-stats** [comment]
@gravesti I have a question about the  `model_fitter` option in the new interface functions. Does it only include [stats_glm_logit](https://causal-lda.github.io/TrialEmulation/latest-tag/reference/stats_glm_logit.html) and [parsnip_model](https://causal-lda.github.io/TrialEmulation/latest-tag/reference/parsnip_model.html)() at the moment? Do we still have the option to use `parglm`?  Thank you.

**Comment by gravesti** [comment]
@lisu-stats I didn't get to implement it yet, but it should be just a few lines. Would it be useful for you?
